// packages/torph/src/svelte/TextMorph.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { DEFAULT_EASING, TextMorph as Morph } from '../lib/text-morph';

  export let text: string;
  export let locale: Intl.LocalesArgument = 'en';
  export let duration: number = 400;
  export let ease: string = DEFAULT_EASING;
  export let debug: boolean = false;
  export let disabled: boolean = false;
  export let respectReducedMotion: boolean = true;
  export let onAnimationStart: (() => void) | undefined = undefined;
  export let onAnimationComplete: (() => void) | undefined = undefined;
  
  let className: string = '';
  export { className as class };
  export let style: string = '';
  export let as: string = 'div';

  let containerRef: HTMLElement;
  let morphInstance: Morph | null = null;

  onMount(() => {
    if (containerRef) {
      morphInstance = new Morph({
        element: containerRef,
        locale,
        duration,
        ease,
        debug,
        disabled,
        respectReducedMotion,
        onAnimationStart,
        onAnimationComplete,
      });
      morphInstance.update(text);
    }
  });

  onDestroy(() => {
    morphInstance?.destroy();
  });

  $: if (morphInstance) {
    morphInstance.update(text);
  }
</script>

<svelte:element this={as} bind:this={containerRef} class={className} {style}>
</svelte:element>

// packages/torph/src/vue/TextMorph.vue
<template>
  <component
    :is="as"
    ref="containerRef"
    :class="props.class"
    :style="props.style"
  ></component>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from "vue";
import { DEFAULT_EASING, TextMorph as Morph } from "../lib/text-morph";
import type { TextMorphProps } from "./types";

const props = withDefaults(defineProps<TextMorphProps>(), {
  locale: "en",
  duration: 400,
  ease: DEFAULT_EASING,
  disabled: false,
  respectReducedMotion: true,
  as: "div",
});

const containerRef = ref<HTMLElement | null>(null);
let morphInstance: Morph | null = null;

onMounted(() => {
  if (containerRef.value) {
    morphInstance = new Morph({
      element: containerRef.value,
      locale: props.locale,
      duration: props.duration,
      ease: props.ease,
      debug: props.debug,
      disabled: props.disabled,
      respectReducedMotion: props.respectReducedMotion,
      onAnimationStart: props.onAnimationStart,
      onAnimationComplete: props.onAnimationComplete,
    });
    morphInstance.update(props.text);
  }
});

onUnmounted(() => {
  morphInstance?.destroy();
});

watch(
  () => props.text,
  (newText) => {
    morphInstance?.update(newText);
  },
);
</script>
