// packages/torph/src/react/TextMorph.tsx
"use client";

import React from "react";
import { DEFAULT_AS, TextMorph as Morph } from "../lib/text-morph";
import type { TextMorphOptions } from "../lib/text-morph/types";

export type TextMorphProps = Omit<TextMorphOptions, "element"> & {
  children: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  as?: React.ElementType;
};

function childrenToString(node: React.ReactNode): string {
  if (typeof node === "string") return node;
  if (typeof node === "number") return String(node);
  if (!node || typeof node === "boolean") return "";
  if (Array.isArray(node)) return node.map(childrenToString).join("");
  if (React.isValidElement(node)) {
    throw new Error(
      "TextMorph only accepts text content. Found a React element — use strings, numbers, or expressions instead."
    );
  }
  throw new Error(
    `TextMorph received an unsupported child of type "${typeof node}".`
  );
}

export const TextMorph = ({
  children,
  className,
  style,
  as = DEFAULT_AS,
  ...props
}: TextMorphProps) => {
  const { ref, update } = useTextMorph(props);
  const text = childrenToString(children);
  const initialHTML = React.useRef({ __html: text });

  React.useEffect(() => {
    update(text);
  }, [text, update]);

  const Component = as;

  return (
    <Component
      ref={ref}
      className={className}
      style={style}
      dangerouslySetInnerHTML={initialHTML.current}
    />
  );
};

export function useTextMorph(props: Omit<TextMorphOptions, "element">) {
  const ref = React.useRef<HTMLDivElement | null>(null);
  const morphRef = React.useRef<Morph | null>(null);

  const configKey = JSON.stringify({
    ease: props.ease,
    duration: props.duration,
    locale: props.locale,
    scale: props.scale,
    disabled: props.disabled,
    respectReducedMotion: props.respectReducedMotion,
  });

  const lastText = React.useRef("");

  React.useEffect(() => {
    if (ref.current) {
      morphRef.current = new Morph({ element: ref.current, ...props });
      if (lastText.current) {
        morphRef.current.update(lastText.current);
      }
    }

    return () => {
      morphRef.current?.destroy();
    };
  }, [configKey]);

  const update = React.useCallback((text: string) => {
    lastText.current = text;
    morphRef.current?.update(text);
  }, []);

  return { ref, update };
}

// packages/torph/src/vue/TextMorph.vue
<template>
  <component
    :is="as"
    ref="containerRef"
    :class="props.class"
    :style="props.style"
  ></component>
</template>

<script setup lang="ts">
import { ref, computed, onUnmounted, watch } from "vue";
import {
  DEFAULT_AS,
  DEFAULT_TEXT_MORPH_OPTIONS,
  TextMorph as Morph,
} from "../lib/text-morph";
import type { TextMorphProps } from "./types";

const props = withDefaults(defineProps<TextMorphProps>(), {
  locale: DEFAULT_TEXT_MORPH_OPTIONS.locale,
  duration: DEFAULT_TEXT_MORPH_OPTIONS.duration,
  ease: DEFAULT_TEXT_MORPH_OPTIONS.ease,
  scale: DEFAULT_TEXT_MORPH_OPTIONS.scale,
  disabled: DEFAULT_TEXT_MORPH_OPTIONS.disabled,
  respectReducedMotion: DEFAULT_TEXT_MORPH_OPTIONS.respectReducedMotion,
  as: DEFAULT_AS,
});

const containerRef = ref<HTMLElement | null>(null);
let morphInstance: Morph | null = null;

const configKey = computed(() =>
  JSON.stringify({
    ease: props.ease,
    duration: props.duration,
    locale: props.locale,
    scale: props.scale,
    disabled: props.disabled,
    respectReducedMotion: props.respectReducedMotion,
  }),
);

function createInstance() {
  morphInstance?.destroy();
  if (containerRef.value) {
    morphInstance = new Morph({
      element: containerRef.value,
      locale: props.locale,
      duration: props.duration,
      ease: props.ease,
      debug: props.debug,
      scale: props.scale,
      disabled: props.disabled,
      respectReducedMotion: props.respectReducedMotion,
      onAnimationStart: props.onAnimationStart,
      onAnimationComplete: props.onAnimationComplete,
    });
    morphInstance.update(props.text);
  }
}

watch(containerRef, () => createInstance(), { flush: "post" });
watch(configKey, () => createInstance());

onUnmounted(() => {
  morphInstance?.destroy();
});

watch(
  () => props.text,
  (newText) => {
    morphInstance?.update(newText);
  },
);
</script>
